create table if not exists public.cash_records (
  id bigint generated by default as identity primary key,
  user_name text not null check (char_length(trim(user_name)) > 0),
  narration text not null check (char_length(trim(narration)) > 0),
  attachment_urls jsonb not null default '[]'::jsonb,
  location_id bigint not null references public.locations (id) on delete restrict,
  status text not null default 'Pending' check (status in ('Pending', 'Approved')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists cash_records_location_id_idx on public.cash_records(location_id);
create index if not exists cash_records_status_idx on public.cash_records(status);

create or replace function public.set_cash_records_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_cash_records_updated_at on public.cash_records;
create trigger trg_cash_records_updated_at
before update on public.cash_records
for each row execute procedure public.set_cash_records_updated_at();

alter table public.cash_records enable row level security;

drop policy if exists "Allow select for cash_records" on public.cash_records;
create policy "Allow select for cash_records"
on public.cash_records
for select
to anon, authenticated
using (true);

drop policy if exists "Allow insert for cash_records" on public.cash_records;
create policy "Allow insert for cash_records"
on public.cash_records
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow update for cash_records" on public.cash_records;
create policy "Allow update for cash_records"
on public.cash_records
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow delete for cash_records" on public.cash_records;
create policy "Allow delete for cash_records"
on public.cash_records
for delete
to anon, authenticated
using (true);
