create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_name text not null check (char_length(trim(user_name)) > 0),
  narration text not null check (char_length(trim(narration)) > 0),
  attachment_urls jsonb not null default '[]'::jsonb,
  expense_value numeric(12, 2) not null check (expense_value > 0),
  location_id bigint not null references public.locations (id) on delete restrict,
  category_id bigint not null references public.categories (id) on delete restrict,
  status text not null default 'Pending' check (status in ('Pending', 'Approved')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists expenses_location_id_idx on public.expenses(location_id);
create index if not exists expenses_category_id_idx on public.expenses(category_id);
create index if not exists expenses_status_idx on public.expenses(status);

create or replace function public.set_expenses_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_expenses_updated_at on public.expenses;
create trigger trg_expenses_updated_at
before update on public.expenses
for each row execute procedure public.set_expenses_updated_at();

alter table public.expenses enable row level security;

drop policy if exists "Allow select for expenses" on public.expenses;
create policy "Allow select for expenses"
on public.expenses
for select
to anon, authenticated
using (true);

drop policy if exists "Allow insert for expenses" on public.expenses;
create policy "Allow insert for expenses"
on public.expenses
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow update for expenses" on public.expenses;
create policy "Allow update for expenses"
on public.expenses
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Allow delete for expenses" on public.expenses;
create policy "Allow delete for expenses"
on public.expenses
for delete
to anon, authenticated
using (true);
